CHANGELOG.md

release/minor release 0.0.1

---

.circleci/config.yml
CHANGELOG.md

Release/minor release v0.0.2

---

.circleci/config.yml
CHANGELOG.md
src/commands/docker-build-image.yml
src/examples/work-with-docker.yml
src/examples/work-with-helm.yml

Release/minor release v0.0.3

---

CHANGELOG.md
README.md
src/@orb.yml
src/commands/helm-build-chart.yml
src/examples/work-with-helm.yml

Release/patch release v0.1.1

---

CHANGELOG.md

Prepare change logs

---

CHANGELOG.md

release/patch release 0.1.3

---

CHANGELOG.md

release/patch release v0.1.4

---

CHANGELOG.md
src/commands/install-cli.yml

Release/patch release v0.1.5

---

CHANGELOG.md
src/@orb.yml
src/commands/helm-install-cli.yml

Release/patch release v0.1.6

---

CHANGELOG.md
fixtures/python/Pipfile
fixtures/python/Pipfile.lock
fixtures/python/pyproject.toml
src/@orb.yml
src/commands/python-install-cli.yml
src/executors/default.yml

Upgrade Python version to v3.8.6

release/patch release v0.1.9

---

CHANGELOG.md
src/commands/install-cli.yml
src/commands/terraform-install-cli.yml

Release/patch release v0.1.11

---

.circleci/config.yml
CHANGELOG.md
src/commands/docker-build-image.yml
src/commands/install-cli.yml
src/examples/work-with-docker.yml

Bump noos-inv to v0.0.7.
Pass optional `--file` argument to command docker.build.

Noosenergy/release/patch release v0.1.12

---

CHANGELOG.md
src/@orb.yml
src/commands/docker-build-image.yml
src/commands/helm-build-chart.yml
src/commands/helm-lint-chart.yml
src/commands/install-cli.yml
src/commands/python-build-wheel.yml
src/commands/python-install-cli.yml
src/commands/python-lint-package.yml
src/commands/python-publish-wheel.yml
src/commands/python-test-package.yml
src/commands/terraform-install-cli.yml
src/commands/terraform-run-plan.yml
src/commands/terraform-update-variable.yml
src/executors/default.yml

Refactoring PR with an additional feature:
Ref:
https://github.com/CircleCI-Public/slack-orb/wiki
https://circleci.com/developer/orbs/orb/circleci/slack#usage-notify_on_fail_with_template

Release/patch release v0.1.14

---

.circleci/config.yml
.circleci/test-deploy.yml

[JIRA NOOS-415](https://noosenergy.atlassian.net/browse/NOOS-415?atlOrigin=eyJpIjoiYjk2NzdiMjg0MDkxNGZiMjlmYjI3ZTQzNThkNDQyYTEiLCJwIjoiaiJ9)

Merge test and publish workflow

---

.circleci/test-deploy.yml

Pub type was missing
https://circleci.com/developer/orbs/orb/circleci/orb-tools#jobs-publish

Add production pub_type in publish job

---

.circleci/test-deploy.yml
CHANGELOG.md
src/commands/docker_build_image.yml

**JIRA reference:** [NOOS-435](https://noosenergy.atlassian.net/browse/NOOS-435)
[NOOS-435]: https://noosenergy.atlassian.net/browse/NOOS-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NOOS-435/add-tag-only-parameter

---

.circleci/test-deploy.yml
README.md
fixtures/python/.gitignore
fixtures/python/Pipfile
fixtures/python/Pipfile.lock

**JIRA Reference**: [NOOS-415](https://noosenergy.atlassian.net/browse/NOOS-415)
[NOOS-415]: https://noosenergy.atlassian.net/browse/NOOS-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NOOS-415/upgrade-python

---

.circleci/test-deploy.yml
CHANGELOG.md
src/commands/docker_build_image.yml
src/commands/docker_buildx_image.yml
src/commands/docker_install_cli.yml

* Add docker layer caching feature
**JIRA Reference:** [NOOS-517](https://noosenergy.atlassian.net/browse/NOOS-517)
[NOOS-517]: https://noosenergy.atlassian.net/browse/NOOS-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NOOS-517/docker-layer-caching

---

CHANGELOG.md
LICENSE
src/executors/postgres.yml

- Add executor with postgres side-car container.
- Prepare release v0.2.3

NOOS-659/postgres-executor

---

.circleci/test-deploy.yml
CHANGELOG.md
src/commands/docker_build_image.yml
src/commands/docker_buildx_image.yml
src/examples/work_with_docker.yml

NOOS-719/change-circleci-timeout

---

.github/workflows/pr_agent_template.yml

NOOS-914/ai-pr-review-template

---

.github/workflows/pr_agent.yml

NOOS-914/ai-pr-review-agent

---

.circleci/config.yml
.circleci/test-deploy.yml
CHANGELOG.md
LICENSE
fixtures/python/pipenv/Pipfile
fixtures/python/pipenv/Pipfile.lock
fixtures/python/pipenv/pyproject.toml
fixtures/python/uv/pyproject.toml
fixtures/python/uv/uv.lock
src/@orb.yml

NOOS-981/upgrade-python-3.12

---

.circleci/test-deploy.yml
CHANGELOG.md
fixtures/python/pipenv/Pipfile
fixtures/python/pipenv/Pipfile.lock
fixtures/python/pipenv/pyproject.toml
fixtures/python/uv/pyproject.toml
fixtures/python/uv/uv.lock
src/commands/python_lint_package.yml
src/examples/work_with_python.yml

NOOS-866/migrate-current-linters-to-ruff

---

CHANGELOG.md
src/executors/postgres.yml
src/executors/timescale.yml

NOOS-1349/update-postgres-version
